version: '3.3'

services:
  wicaradmin:
    container_name: client
    build:
      context: ./wicaradminfront
      dockerfile: Dockerfile-dev
      args:
        - NODE_ENV=development


    image: todhm/adminfront:latest
    volumes:
        - ./wicaradminfront:/opt/app:delegated
        - ./wicaradminfront/package.json:/opt/package.json
        - ./wicaradminfront/package-lock.json:/opt/package-lock.json
        - frontend-node-modules:/opt/app/node_modules
    ports:
        - "3000:3000"
  
    networks:
    - frontend
    environment:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=http://10.10.36.54:8000
        - CHOKIDAR_USEPOLLING=true
        - GENERATE_SOURCEMAP=false


volumes:
  frontend-node-modules:

networks:
    frontend:
