version: '3.3'

services:
  wicaradmin:
    image: todhm/adminfront:latest
    ports:
        - "80:80"


    environment:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=http://localhost:5000
        - CHOKIDAR_USEPOLLING=true
        - GENERATE_SOURCEMAP=false
