version: '3.3'

services:
  wicaradmin:
    image: todhm/adminfront:latest
    ports:
        - "3000:3000"


    environment:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=http://ec2-13-125-55-210.ap-northeast-2.compute.amazonaws.com:5000
        - CHOKIDAR_USEPOLLING=true
        - GENERATE_SOURCEMAP=false
